#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -s "${ZDOTDIR:-$HOME}/.environment" ]]; then
  source "${ZDOTDIR:-$HOME}/.environment"
fi


setopt NO_SHARE_HISTORY
setopt CLOBBER
unsetopt CORRECT
unsetopt CORRECT_ALL
unsetopt NOMATCH
setopt RMSTARSILENT

bindkey ';5D' emacs-backward-word
bindkey ';5C' emacs-forward-word

unalias rm
alias rm='nocorrect rm'
unalias cp
alias cp='nocorrect cp'

source /etc/profile.d/vte.sh

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/mc mc

source /home/sven/.config/broot/launcher/bash/br
